// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using totvs_test;

namespace totvs_test.Migrations
{
    [DbContext(typeof(TotvsDbContext))]
    [Migration("20200923002901_AddTotvsUser")]
    partial class AddTotvsUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("totvs_test.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialValue")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("totvs_test.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("97abbeca-c716-4eb0-b1da-d0e7287118b3"),
                            Email = "guilherme.neubaner@gmail.com",
                            Enabled = true,
                            Name = "Guilherme Neubaner",
                            Password = "$2a$11$3d6RFjwQoG6Fww0CGZFRDOE1g2O09oP3RQKdT1cIzI2iW/2zY5/cG"
                        },
                        new
                        {
                            Id = new Guid("efe1f695-4048-4ef8-939e-017fe39cba01"),
                            Email = "admin@totvs.com.br",
                            Enabled = true,
                            Name = "TOTVS Admin",
                            Password = "$2a$11$.BURPJNoyvJVnR4McOrCgudndd2nxuVW2dFUMg.nLWQZXWoarQ4T."
                        });
                });

            modelBuilder.Entity("totvs_test.Auction", b =>
                {
                    b.HasOne("totvs_test.User", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
